### ISSUE TITLE
Using [~] RULES where possible

### ISSUE THREAD

**Issue by andygill** [ku-fpg/natural-transformation#8]
@xich - why do we not want to use RULES in this package? I like the documentation being executable. I remember you gave a good reason why not to use them, but do not remember the details.

**Comment by RyanGlScott** [comment]
Are you referring to [this comment](https://github.com/ku-fpg/natural-transformation/issues/4#issuecomment-77967313)?

Personally, I'm not crazy about [this rewrite rule](https://github.com/ku-fpg/wakarusa/blob/264a10129233aa7b9fbff1ffa81cd104bf057b89/src/Control/Natural.hs#L22):

``` haskell
{-# RULES "natural free theorem" [~] 
    forall h (r :: (Functor f, Functor g, Transformation f g t) => t) . 
    fmap h . (r #) = (r #) . fmap h 
  #-}
```

since I can't see what kind of optimization it provides. It simply favors `(r #) . fmap h` over `fmap h . (r #)`. As opposed to something like this:

``` haskell
  {-# RULES
  "map/map"    forall f g xs.  map f (map g xs) = map (f.g) xs
    #-}
```

This clearly provides a benefit, since it avoids allocating an extra list by only calling `map` once. With the former rule, it seems a lot harder to justify.

**Comment by xich** [comment]
Yeah, the thread @RyanGlScott linked to is the gist of it. Inactive rules are still stored as annotations on bindings like any other rule, so their free variables are included when computing free variables, and they affect SCC analysis because they potentially link otherwise-unrelated bindings. This can have subtle effects on other optimizations.

Granted, I have no concrete example to demonstrate this, so all I can say is "it might change things" rather than "it will change things".

**Comment by andygill** [comment]
I don't mind the fact that there is no optimization. (Moving an `fmap` **may** allow it to fuse with another `fmap`, for example.) And I'm unconvinced by the broken optimization. I'd rather put the `RULES` in, and see what it breaks in the future. Feel free to say "I told you so" when it goes wrong.

**Comment by andygill** [comment]
I've put the RULES into a RULES module. Best of both worlds.
